-- Insert sample profiles for testing (without subscribers data for now)
INSERT INTO public.profiles (
  id,
  name,
  age,
  bio,
  location,
  occupation,
  education,
  interests,
  avatar_url,
  photos,
  gender,
  date_of_birth,
  height,
  relationship_goals,
  personality_type,
  communication_style,
  looking_for,
  is_premium,
  created_at
) VALUES
(
  gen_random_uuid(),
  'Alex Chen',
  28,
  'Software engineer who loves hiking and coffee. Always up for a good conversation about tech, travel, or philosophy. Looking for genuine connections.',
  'San Francisco, CA',
  'Software Engineer',
  'Computer Science, Stanford',
  ARRAY['hiking', 'coffee', 'technology', 'travel', 'photography', 'cooking'],
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face',
  ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=800&fit=crop'],
  'male',
  '1995-03-15',
  180,
  'long-term relationship',
  'ENFP',
  'direct but warm',
  'someone adventurous',
  true,
  NOW() - INTERVAL '2 days'
),
(
  gen_random_uuid(),
  'Maya Rodriguez',
  26,
  'Artist and yoga instructor. I believe in mindful living and creating beautiful moments. Love deep conversations and spontaneous adventures.',
  'Austin, TX',
  'Yoga Instructor & Artist',
  'Fine Arts, UT Austin',
  ARRAY['yoga', 'art', 'meditation', 'nature', 'music', 'wellness'],
  'https://images.unsplash.com/photo-1494790108755-2616b612b2e5?w=400&h=400&fit=crop&crop=face',
  ARRAY['https://images.unsplash.com/photo-1494790108755-2616b612b2e5?w=600&h=800&fit=crop'],
  'female',
  '1997-08-22',
  165,
  'meaningful connection',
  'INFP',
  'thoughtful and empathetic',
  'creative soul',
  false,
  NOW() - INTERVAL '1 day'
),
(
  gen_random_uuid(),
  'Jordan Kim',
  30,
  'Doctor by day, foodie by night. I travel whenever I can and love trying new cuisines. Looking for someone to explore the world with.',
  'Seattle, WA',
  'Emergency Medicine Physician',
  'Medicine, Johns Hopkins',
  ARRAY['travel', 'food', 'medicine', 'running', 'languages', 'wine'],
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face',
  ARRAY['https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=600&h=800&fit=crop'],
  'male',
  '1993-12-10',
  175,
  'long-term relationship',
  'INTJ',
  'analytical but caring',
  'travel companion',
  true,
  NOW() - INTERVAL '3 days'
),
(
  gen_random_uuid(),
  'Zoe Williams',
  24,
  'Marketing creative with a passion for sustainability. I love live music, farmers markets, and making the world a better place.',
  'Portland, OR',
  'Marketing Creative',
  'Communications, Portland State',
  ARRAY['sustainability', 'music', 'marketing', 'volunteering', 'cycling', 'books'],
  'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face',
  ARRAY['https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=600&h=800&fit=crop'],
  'female',
  '1999-05-18',
  170,
  'exploring possibilities',
  'ENFJ',
  'enthusiastic and genuine',
  'someone with values',
  false,
  NOW() - INTERVAL '4 hours'
),
(
  gen_random_uuid(),
  'Marcus Thompson',
  32,
  'Architect who designs sustainable buildings. Rock climbing enthusiast and weekend warrior. Believe in work hard, play harder.',
  'Denver, CO',
  'Sustainable Architect',
  'Architecture, CU Boulder',
  ARRAY['architecture', 'rock climbing', 'sustainability', 'design', 'outdoors', 'craft beer'],
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face',
  ARRAY['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&h=800&fit=crop'],
  'male',
  '1991-09-03',
  185,
  'life partner',
  'ESTP',
  'energetic and honest',
  'adventure buddy',
  true,
  NOW() - INTERVAL '6 hours'
),
(
  gen_random_uuid(),
  'Priya Patel',
  27,
  'UX designer who loves solving problems and creating delightful experiences. Board game enthusiast and amateur chef.',
  'New York, NY',
  'UX Designer',
  'Design, Parsons',
  ARRAY['design', 'technology', 'board games', 'cooking', 'theater', 'psychology'],
  'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&crop=face',
  ARRAY['https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&h=800&fit=crop'],
  'female',
  '1996-11-27',
  162,
  'meaningful connection',
  'INFJ',
  'reflective and warm',
  'intellectual connection',
  false,
  NOW() - INTERVAL '12 hours'
),
(
  gen_random_uuid(),
  'Jake Sullivan',
  29,
  'Marine biologist passionate about ocean conservation. Love diving, surfing, and beach volleyball. Looking for someone who shares my love for the ocean.',
  'San Diego, CA',
  'Marine Biologist',
  'Marine Biology, Scripps',
  ARRAY['marine biology', 'surfing', 'diving', 'conservation', 'beach volleyball', 'photography'],
  'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&h=400&fit=crop&crop=face',
  ARRAY['https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=600&h=800&fit=crop'],
  'male',
  '1994-07-14',
  178,
  'long-term relationship',
  'ISFP',
  'laid-back and passionate',
  'ocean lover',
  true,
  NOW() - INTERVAL '18 hours'
),
(
  gen_random_uuid(),
  'Elena Rossi',
  25,
  'Journalist covering environmental issues. I love storytelling, live music, and discovering hidden gems in the city. Always curious about the world.',
  'Chicago, IL',
  'Environmental Journalist',
  'Journalism, Northwestern',
  ARRAY['journalism', 'environment', 'writing', 'music', 'politics', 'coffee'],
  'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400&h=400&fit=crop&crop=face',
  ARRAY['https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=600&h=800&fit=crop'],
  'female',
  '1998-02-09',
  168,
  'exploring possibilities',
  'ENTP',
  'curious and articulate',
  'storyteller',
  false,
  NOW() - INTERVAL '1 day 6 hours'
);