// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syptmdowisipzqaxoroq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5cHRtZG93aXNpcHpxYXhvcm9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0ODMwMTAsImV4cCI6MjA2NzA1OTAxMH0.ACxyOW_eqSeQFrvrMNVpYHiTqipqUHKF9gjAjhvJg60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});